# Como Rodar Código em Paralelo no Python - Como Acelerar o seu Código
https://youtu.be/maj47xd_R7g

## Dependências

In [1]:
""!pip install pandas openpyxl joblib""

Requirement already satisfied: pandas in /opt/conda/lib/python3.10/site-packages (1.5.0)
Requirement already satisfied: openpyxl in /opt/conda/lib/python3.10/site-packages (3.0.10)
Requirement already satisfied: joblib in /opt/conda/lib/python3.10/site-packages (1.2.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/conda/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas) (2022.4)
Requirement already satisfied: numpy>=1.21.0 in /opt/conda/lib/python3.10/site-packages (from pandas) (1.23.3)
Requirement already satisfied: et-xmlfile in /opt/conda/lib/python3.10/site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [2]:
from zipfile import ZipFile
from pathlib import Path
import pandas as pd
import time

## Acessar conteúdo do ZipFile sem descompactar no disco

In [3]:
with ZipFile('drive-download-20221008T154045Z-001.zip') as zfile:
    zfile.printdir()

File Name                                             Modified             Size
Salvador Shopping.xlsx                         2021-10-25 06:50:38        15459
Shopping Midway Mall.xlsx                      2021-10-25 06:50:38        14199
Passei das Águas Shopping.xlsx                 2021-10-25 06:50:36        15047
Codigo em Paralelo.ipynb                       2021-11-10 05:28:22         1155
Shopping Ibirapuera.xlsx                       2021-10-25 06:50:38        14528
Shopping Center Interlagos.xlsx                2021-10-25 06:50:38        13959
Iguatemi Esplanada.xlsx                        2021-10-25 06:50:38        14098
Shopping Morumbi.xlsx                          2021-10-25 06:50:36        15583
Shopping Vila Velha.xlsx                       2021-10-25 06:50:38        15297
Shopping União de Osasco.xlsx                  2021-10-25 06:50:36        14883
Ribeirão Shopping.xlsx                         2021-10-25 06:50:38        14687
Shopping SP Market.xlsx                        2021-10-25 06:50:36        14499
Norte Shopping.xlsx                            2021-10-25 06:50:38        14037
Shopping Barra.xlsx                            2021-10-25 06:50:38        14160
Iguatemi Campinas.xlsx                         2021-10-25 06:50:36        15866
Shopping Eldorado.xlsx                         2021-10-25 06:50:38        15436
Shopping Iguatemi Fortaleza.xlsx               2021-10-25 06:50:38        15159
Palladium Shopping Curitiba.xlsx               2021-10-25 06:50:38        15432
Shopping Center Leste Aricanduva.xlsx          2021-10-25 06:50:38        13209
Rio Mar Recife.xlsx                            2021-10-25 06:50:38        17350
Novo Shopping Ribeirão Preto.xlsx              2021-10-25 06:50:38        13558
Shopping Recife.xlsx                           2021-10-25 06:50:38        14953
Parque Dom Pedro Shopping.xlsx                 2021-10-25 06:50:38        15069
Rio Mar Shopping Fortaleza.xlsx                2021-10-25 06:50:36        15147

In [4]:
with ZipFile('drive-download-20221008T154045Z-001.zip') as zfile:
    listfiles = zfile.filelist

In [5]:
for file in listfiles:
    print(file.filename)

Salvador Shopping.xlsx
Shopping Midway Mall.xlsx
Passei das Águas Shopping.xlsx
Codigo em Paralelo.ipynb
Shopping Ibirapuera.xlsx
Shopping Center Interlagos.xlsx
Iguatemi Esplanada.xlsx
Shopping Morumbi.xlsx
Shopping Vila Velha.xlsx
Shopping União de Osasco.xlsx
Ribeirão Shopping.xlsx
Shopping SP Market.xlsx
Norte Shopping.xlsx
Shopping Barra.xlsx
Iguatemi Campinas.xlsx
Shopping Eldorado.xlsx
Shopping Iguatemi Fortaleza.xlsx
Palladium Shopping Curitiba.xlsx
Shopping Center Leste Aricanduva.xlsx
Rio Mar Recife.xlsx
Novo Shopping Ribeirão Preto.xlsx
Shopping Recife.xlsx
Parque Dom Pedro Shopping.xlsx
Rio Mar Shopping Fortaleza.xlsx

In [6]:
with ZipFile('drive-download-20221008T154045Z-001.zip') as zfile:
    listfiles = zfile.namelist()
    filename = listfiles[0]
    fin = zfile.read(filename)
    display(pd.read_excel(fin))

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65047,2019-12-01,Salvador Shopping,Calça Listrado,1,181,181
1,65047,2019-12-01,Salvador Shopping,Bermuda Xadrez,5,155,775
2,65047,2019-12-01,Salvador Shopping,Terno Listrado,3,709,2127
3,65104,2019-12-01,Salvador Shopping,Terno Estampa,5,706,3530
4,65111,2019-12-01,Salvador Shopping,Tênis Linho,1,294,294
...,...,...,...,...,...,...,...
297,69846,2019-12-25,Salvador Shopping,Short Estampa,2,96,192
298,69846,2019-12-25,Salvador Shopping,Tênis Estampa,5,256,1280
299,69850,2019-12-25,Salvador Shopping,Calça Estampa,4,177,708
300,69972,2019-12-26,Salvador Shopping,Terno Liso,3,720,2160
301,69972,2019-12-26,Salvador Shopping,Sapato Estampa,5,358,1790

In [7]:
# Acessa cada arquivo contido no zipfile e transforma em exibe seu Dataframe

with ZipFile('drive-download-20221008T154045Z-001.zip') as zfile:
    for filename in zfile.namelist():
        if filename.endswith('.xlsx'):
            fin = zfile.read(filename)
            display(pd.read_excel(fin))

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65047,2019-12-01,Salvador Shopping,Calça Listrado,1,181,181
1,65047,2019-12-01,Salvador Shopping,Bermuda Xadrez,5,155,775
2,65047,2019-12-01,Salvador Shopping,Terno Listrado,3,709,2127
3,65104,2019-12-01,Salvador Shopping,Terno Estampa,5,706,3530
4,65111,2019-12-01,Salvador Shopping,Tênis Linho,1,294,294
...,...,...,...,...,...,...,...
297,69846,2019-12-25,Salvador Shopping,Short Estampa,2,96,192
298,69846,2019-12-25,Salvador Shopping,Tênis Estampa,5,256,1280
299,69850,2019-12-25,Salvador Shopping,Calça Estampa,4,177,708
300,69972,2019-12-26,Salvador Shopping,Terno Liso,3,720,2160
301,69972,2019-12-26,Salvador Shopping,Sapato Estampa,5,358,1790

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65095,2019-12-01,Shopping Midway Mall,Pulseira Liso,1,87,87
1,65108,2019-12-01,Shopping Midway Mall,Meia Estampa,2,50,100
2,65120,2019-12-01,Shopping Midway Mall,Sapato,2,350,700
3,65124,2019-12-01,Shopping Midway Mall,Camisa Gola V Estampa,5,118,590
4,65140,2019-12-01,Shopping Midway Mall,Cueca Xadrez,2,60,120
...,...,...,...,...,...,...,...
254,69914,2019-12-25,Shopping Midway Mall,Short Liso,2,108,216
255,69914,2019-12-25,Shopping Midway Mall,Cinto,5,200,1000
256,69919,2019-12-25,Shopping Midway Mall,Cinto Xadrez,3,215,645
257,69929,2019-12-25,Shopping Midway Mall,Meia Listrado,2,37,74
258,69994,2019-12-26,Shopping Midway Mall,Calça,1,170,170

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65024,2019-12-01,Passei das Águas Shopping,Camiseta Estampa,2,196,392
1,65102,2019-12-01,Passei das Águas Shopping,Camisa Gola V Xadrez,2,107,214
2,65109,2019-12-01,Passei das Águas Shopping,Camiseta Estampa,5,196,980
3,65112,2019-12-01,Passei das Águas Shopping,Pulseira Linho,1,114,114
4,65123,2019-12-01,Passei das Águas Shopping,Camiseta Xadrez,2,200,400
...,...,...,...,...,...,...,...
284,69745,2019-12-24,Passei das Águas Shopping,Camiseta,3,180,540
285,69861,2019-12-25,Passei das Águas Shopping,Terno Linho,5,750,3750
286,69861,2019-12-25,Passei das Águas Shopping,Camiseta Xadrez,2,200,400
287,69937,2019-12-25,Passei das Águas Shopping,Sunga Xadrez,5,116,580
288,69957,2019-12-25,Passei das Águas Shopping,Bermuda Estampa,1,169,169

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65025,2019-12-01,Shopping Ibirapuera,Calça Xadrez,5,185,925
1,65025,2019-12-01,Shopping Ibirapuera,Short Listrado,1,102,102
2,65025,2019-12-01,Shopping Ibirapuera,Meia Listrado,1,37,37
3,65058,2019-12-01,Shopping Ibirapuera,Meia Estampa,2,50,100
4,65058,2019-12-01,Shopping Ibirapuera,Sunga Estampa,2,120,240
...,...,...,...,...,...,...,...
268,69880,2019-12-25,Shopping Ibirapuera,Mochila Xadrez,2,283,566
269,69941,2019-12-25,Shopping Ibirapuera,Cueca Liso,5,69,345
270,69946,2019-12-25,Shopping Ibirapuera,Calça Xadrez,1,185,185
271,69946,2019-12-25,Shopping Ibirapuera,Gorro Xadrez,1,85,85
272,69977,2019-12-26,Shopping Ibirapuera,Camisa Gola V Estampa,1,118,118

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65031,2019-12-01,Shopping Center Interlagos,Meia Liso,4,38,152
1,65045,2019-12-01,Shopping Center Interlagos,Pulseira,2,70,140
2,65074,2019-12-01,Shopping Center Interlagos,Relógio,1,200,200
3,65074,2019-12-01,Shopping Center Interlagos,Tênis Liso,1,266,266
4,65182,2019-12-01,Shopping Center Interlagos,Bermuda,1,150,150
...,...,...,...,...,...,...,...
249,69907,2019-12-25,Shopping Center Interlagos,Pulseira,1,70,70
250,69926,2019-12-25,Shopping Center Interlagos,Short Liso,1,108,108
251,69926,2019-12-25,Shopping Center Interlagos,Calça Linho,1,211,211
252,69978,2019-12-26,Shopping Center Interlagos,Gorro Xadrez,2,85,170
253,69978,2019-12-26,Shopping Center Interlagos,Terno Estampa,2,706,1412

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65049,2019-12-01,Iguatemi Esplanada,Terno Linho,5,750,3750
1,65049,2019-12-01,Iguatemi Esplanada,Gorro Xadrez,1,85,85
2,65081,2019-12-01,Iguatemi Esplanada,Relógio Liso,3,216,648
3,65081,2019-12-01,Iguatemi Esplanada,Cinto Liso,3,209,627
4,65081,2019-12-01,Iguatemi Esplanada,Bermuda Xadrez,1,155,155
...,...,...,...,...,...,...,...
253,69899,2019-12-25,Iguatemi Esplanada,Sapato Xadrez,4,368,1472
254,69903,2019-12-25,Iguatemi Esplanada,Terno Liso,5,720,3600
255,69928,2019-12-25,Iguatemi Esplanada,Meia,1,30,30
256,69944,2019-12-25,Iguatemi Esplanada,Gorro Xadrez,5,85,425
257,69944,2019-12-25,Iguatemi Esplanada,Sapato Xadrez,2,368,736

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65014,2019-12-01,Shopping Morumbi,Sunga Listrado,5,114,570
1,65014,2019-12-01,Shopping Morumbi,Casaco Listrado,1,269,269
2,65020,2019-12-01,Shopping Morumbi,Pulseira Listrado,4,79,316
3,65020,2019-12-01,Shopping Morumbi,Camiseta Xadrez,5,200,1000
4,65020,2019-12-01,Shopping Morumbi,Camisa Listrado,2,108,216
...,...,...,...,...,...,...,...
301,69877,2019-12-25,Shopping Morumbi,Polo Xadrez,2,142,284
302,69877,2019-12-25,Shopping Morumbi,Polo,1,130,130
303,69904,2019-12-25,Shopping Morumbi,Polo Linho,1,176,176
304,69904,2019-12-25,Shopping Morumbi,Gorro Listrado,3,97,291
305,69931,2019-12-25,Shopping Morumbi,Gorro Liso,3,92,276

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65034,2019-12-01,Shopping Vila Velha,Camisa Gola V Liso,4,118,472
1,65034,2019-12-01,Shopping Vila Velha,Sapato Linho,5,391,1955
2,65057,2019-12-01,Shopping Vila Velha,Pulseira Listrado,2,79,158
3,65128,2019-12-01,Shopping Vila Velha,Camisa Estampa,1,113,113
4,65129,2019-12-01,Shopping Vila Velha,Cinto Listrado,2,214,428
...,...,...,...,...,...,...,...
294,69801,2019-12-25,Shopping Vila Velha,Bermuda,3,150,450
295,69859,2019-12-25,Shopping Vila Velha,Meia Liso,2,38,76
296,69970,2019-12-26,Shopping Vila Velha,Casaco Linho,2,299,598
297,69974,2019-12-26,Shopping Vila Velha,Meia Listrado,3,37,111
298,69985,2019-12-26,Shopping Vila Velha,Pulseira Linho,2,114,228

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65019,2019-12-01,Shopping União de Osasco,Polo Xadrez,2,142,284
1,65019,2019-12-01,Shopping União de Osasco,Tênis Linho,1,294,294
2,65055,2019-12-01,Shopping União de Osasco,Camiseta Estampa,2,196,392
3,65055,2019-12-01,Shopping União de Osasco,Gorro Listrado,2,97,194
4,65126,2019-12-01,Shopping União de Osasco,Sunga Estampa,1,120,120
...,...,...,...,...,...,...,...
279,69940,2019-12-25,Shopping União de Osasco,Polo Xadrez,2,142,284
280,69940,2019-12-25,Shopping União de Osasco,Camisa Estampa,2,113,226
281,69979,2019-12-26,Shopping União de Osasco,Camisa Gola V,2,100,200
282,69979,2019-12-26,Shopping União de Osasco,Mochila Estampa,3,277,831
283,69979,2019-12-26,Shopping União de Osasco,Polo Linho,1,176,176

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65070,2019-12-01,Ribeirão Shopping,Tênis Estampa,3,256,768
1,65070,2019-12-01,Ribeirão Shopping,Terno,1,700,700
2,65070,2019-12-01,Ribeirão Shopping,Camisa,2,100,200
3,65072,2019-12-01,Ribeirão Shopping,Bermuda Liso,5,157,785
4,65096,2019-12-01,Ribeirão Shopping,Mochila Linho,1,311,311
...,...,...,...,...,...,...,...
272,69967,2019-12-25,Ribeirão Shopping,Short,1,90,90
273,69967,2019-12-25,Ribeirão Shopping,Bermuda Linho,1,195,195
274,69984,2019-12-26,Ribeirão Shopping,Cueca Liso,4,69,276
275,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108
276,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65017,2019-12-01,Shopping SP Market,Gorro Liso,3,92,276
1,65044,2019-12-01,Shopping SP Market,Camisa Linho,1,141,141
2,65044,2019-12-01,Shopping SP Market,Short Linho,1,133,133
3,65076,2019-12-01,Shopping SP Market,Cueca Linho,1,93,93
4,65076,2019-12-01,Shopping SP Market,Camiseta Linho,1,223,223
...,...,...,...,...,...,...,...
267,69960,2019-12-25,Shopping SP Market,Polo,2,130,260
268,69960,2019-12-25,Shopping SP Market,Sapato Liso,1,368,368
269,69960,2019-12-25,Shopping SP Market,Sapato Estampa,3,358,1074
270,69969,2019-12-25,Shopping SP Market,Pulseira Liso,1,87,87
271,69969,2019-12-25,Shopping SP Market,Camiseta Liso,2,187,374

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65027,2019-12-01,Norte Shopping,Relógio Listrado,1,218,218
1,65179,2019-12-01,Norte Shopping,Gorro Xadrez,1,85,85
2,65179,2019-12-01,Norte Shopping,Bermuda,2,150,300
3,65179,2019-12-01,Norte Shopping,Camisa Gola V Xadrez,5,107,535
4,65179,2019-12-01,Norte Shopping,Camisa,2,100,200
...,...,...,...,...,...,...,...
250,69888,2019-12-25,Norte Shopping,Tênis Linho,1,294,294
251,69916,2019-12-25,Norte Shopping,Terno,2,700,1400
252,69962,2019-12-25,Norte Shopping,Meia Linho,2,78,156
253,69976,2019-12-26,Norte Shopping,Tênis Xadrez,1,259,259
254,69976,2019-12-26,Norte Shopping,Casaco,4,250,1000

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65080,2019-12-01,Shopping Barra,Cueca Liso,1,69,69
1,65080,2019-12-01,Shopping Barra,Terno Xadrez,1,709,709
2,65117,2019-12-01,Shopping Barra,Cinto Xadrez,1,215,215
3,65117,2019-12-01,Shopping Barra,Mochila Liso,3,276,828
4,65118,2019-12-01,Shopping Barra,Sapato,5,350,1750
...,...,...,...,...,...,...,...
255,69908,2019-12-25,Shopping Barra,Meia Liso,2,38,76
256,69908,2019-12-25,Shopping Barra,Camisa,1,100,100
257,69913,2019-12-25,Shopping Barra,Gorro,1,80,80
258,69913,2019-12-25,Shopping Barra,Cinto Linho,1,248,248
259,69950,2019-12-25,Shopping Barra,Cinto Linho,1,248,248

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65016,2019-12-01,Iguatemi Campinas,Sapato Listrado,2,363,726
1,65016,2019-12-01,Iguatemi Campinas,Casaco,1,250,250
2,65028,2019-12-01,Iguatemi Campinas,Sapato,5,350,1750
3,65028,2019-12-01,Iguatemi Campinas,Pulseira Xadrez,1,87,87
4,65033,2019-12-01,Iguatemi Campinas,Casaco Estampa,1,256,256
...,...,...,...,...,...,...,...
310,69934,2019-12-25,Iguatemi Campinas,Chinelo Estampa,3,74,222
311,69934,2019-12-25,Iguatemi Campinas,Camisa Xadrez,2,105,210
312,69934,2019-12-25,Iguatemi Campinas,Tênis Liso,2,266,532
313,69934,2019-12-25,Iguatemi Campinas,Casaco Listrado,1,269,269
314,69939,2019-12-25,Iguatemi Campinas,Bermuda Liso,5,157,785

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65144,2019-12-01,Shopping Eldorado,Calça Xadrez,1,185,185
1,65159,2019-12-01,Shopping Eldorado,Mochila Linho,2,311,622
2,65160,2019-12-01,Shopping Eldorado,Pulseira Estampa,5,87,435
3,65160,2019-12-01,Shopping Eldorado,Gorro,1,80,80
4,65160,2019-12-01,Shopping Eldorado,Short Xadrez,1,100,100
...,...,...,...,...,...,...,...
299,69959,2019-12-25,Shopping Eldorado,Polo Liso,4,137,548
300,69959,2019-12-25,Shopping Eldorado,Camisa Linho,3,141,423
301,69959,2019-12-25,Shopping Eldorado,Cueca Xadrez,1,60,60
302,69986,2019-12-26,Shopping Eldorado,Cueca Estampa,4,66,264
303,69986,2019-12-26,Shopping Eldorado,Terno Listrado,3,709,2127

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65030,2019-12-01,Shopping Iguatemi Fortaleza,Relógio Liso,1,216,216
1,65030,2019-12-01,Shopping Iguatemi Fortaleza,Camisa Gola V Xadrez,1,107,107
2,65032,2019-12-01,Shopping Iguatemi Fortaleza,Sunga,2,100,200
3,65032,2019-12-01,Shopping Iguatemi Fortaleza,Pulseira Estampa,3,87,261
4,65038,2019-12-01,Shopping Iguatemi Fortaleza,Sunga Linho,5,149,745
...,...,...,...,...,...,...,...
285,69910,2019-12-25,Shopping Iguatemi Fortaleza,Chinelo Liso,2,71,142
286,69910,2019-12-25,Shopping Iguatemi Fortaleza,Relógio Listrado,2,218,436
287,69968,2019-12-25,Shopping Iguatemi Fortaleza,Polo Linho,1,176,176
288,69968,2019-12-25,Shopping Iguatemi Fortaleza,Camisa Estampa,3,113,339
289,69968,2019-12-25,Shopping Iguatemi Fortaleza,Cueca Liso,5,69,345

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65043,2019-12-01,Palladium Shopping Curitiba,Casaco,1,250,250
1,65043,2019-12-01,Palladium Shopping Curitiba,Short Xadrez,1,100,100
2,65043,2019-12-01,Palladium Shopping Curitiba,Calça,5,170,850
3,65043,2019-12-01,Palladium Shopping Curitiba,Meia Xadrez,3,41,123
4,65132,2019-12-01,Palladium Shopping Curitiba,Gorro Listrado,2,97,194
...,...,...,...,...,...,...,...
296,69872,2019-12-25,Palladium Shopping Curitiba,Camiseta Listrado,1,197,197
297,69947,2019-12-25,Palladium Shopping Curitiba,Camisa Gola V Liso,2,118,236
298,69956,2019-12-25,Palladium Shopping Curitiba,Mochila Linho,1,311,311
299,69980,2019-12-26,Palladium Shopping Curitiba,Casaco Linho,1,299,299
300,69983,2019-12-26,Palladium Shopping Curitiba,Meia Xadrez,2,41,82

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65053,2019-12-01,Shopping Center Leste Aricanduva,Camisa Gola V Estampa,4,118,472
1,65100,2019-12-01,Shopping Center Leste Aricanduva,Camisa Gola V Estampa,1,118,118
2,65100,2019-12-01,Shopping Center Leste Aricanduva,Short,4,90,360
3,65100,2019-12-01,Shopping Center Leste Aricanduva,Sunga Linho,2,149,298
4,65100,2019-12-01,Shopping Center Leste Aricanduva,Gorro,4,80,320
...,...,...,...,...,...,...,...
225,69922,2019-12-25,Shopping Center Leste Aricanduva,Meia,1,30,30
226,69922,2019-12-25,Shopping Center Leste Aricanduva,Cinto Linho,1,248,248
227,69922,2019-12-25,Shopping Center Leste Aricanduva,Short Xadrez,2,100,200
228,69975,2019-12-26,Shopping Center Leste Aricanduva,Cueca Estampa,5,66,330
229,69975,2019-12-26,Shopping Center Leste Aricanduva,Bermuda Xadrez,1,155,155

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65036,2019-12-01,Rio Mar Recife,Calça,1,170,170
1,65050,2019-12-01,Rio Mar Recife,Camisa Gola V Xadrez,2,107,214
2,65093,2019-12-01,Rio Mar Recife,Bermuda Xadrez,3,155,465
3,65093,2019-12-01,Rio Mar Recife,Calça Listrado,1,181,181
4,65093,2019-12-01,Rio Mar Recife,Casaco Xadrez,1,259,259
...,...,...,...,...,...,...,...
361,69905,2019-12-25,Rio Mar Recife,Mochila Listrado,2,275,550
362,69905,2019-12-25,Rio Mar Recife,Camisa Xadrez,3,105,315
363,69905,2019-12-25,Rio Mar Recife,Tênis Liso,3,266,798
364,69954,2019-12-25,Rio Mar Recife,Chinelo,3,60,180
365,69954,2019-12-25,Rio Mar Recife,Casaco Listrado,3,269,807

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65051,2019-12-01,Novo Shopping Ribeirão Preto,Polo,1,130,130
1,65082,2019-12-01,Novo Shopping Ribeirão Preto,Terno Listrado,4,709,2836
2,65091,2019-12-01,Novo Shopping Ribeirão Preto,Short Listrado,3,102,306
3,65091,2019-12-01,Novo Shopping Ribeirão Preto,Casaco Xadrez,1,259,259
4,65113,2019-12-01,Novo Shopping Ribeirão Preto,Tênis Liso,1,266,266
...,...,...,...,...,...,...,...
234,69981,2019-12-26,Novo Shopping Ribeirão Preto,Camiseta Estampa,1,196,196
235,69981,2019-12-26,Novo Shopping Ribeirão Preto,Meia Linho,1,78,78
236,69981,2019-12-26,Novo Shopping Ribeirão Preto,Sunga Listrado,2,114,228
237,69995,2019-12-26,Novo Shopping Ribeirão Preto,Cinto Listrado,3,214,642
238,69995,2019-12-26,Novo Shopping Ribeirão Preto,Mochila,4,270,1080

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65064,2019-12-01,Shopping Recife,Short Linho,2,133,266
1,65071,2019-12-01,Shopping Recife,Cueca Xadrez,3,60,180
2,65071,2019-12-01,Shopping Recife,Camisa,2,100,200
3,65071,2019-12-01,Shopping Recife,Meia Xadrez,2,41,82
4,65071,2019-12-01,Shopping Recife,Polo Linho,5,176,880
...,...,...,...,...,...,...,...
281,69925,2019-12-25,Shopping Recife,Gorro Liso,2,92,184
282,69936,2019-12-25,Shopping Recife,Terno Linho,1,750,750
283,69971,2019-12-26,Shopping Recife,Cinto Liso,2,209,418
284,69971,2019-12-26,Shopping Recife,Bermuda Listrado,2,163,326
285,69982,2019-12-26,Shopping Recife,Mochila Linho,2,311,622

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65037,2019-12-01,Parque Dom Pedro Shopping,Terno Xadrez,1,709,709
1,65037,2019-12-01,Parque Dom Pedro Shopping,Gorro Xadrez,1,85,85
2,65037,2019-12-01,Parque Dom Pedro Shopping,Cueca Xadrez,1,60,60
3,65037,2019-12-01,Parque Dom Pedro Shopping,Calça Linho,1,211,211
4,65037,2019-12-01,Parque Dom Pedro Shopping,Camisa Gola V,5,100,500
...,...,...,...,...,...,...,...
285,69796,2019-12-25,Parque Dom Pedro Shopping,Tênis Liso,4,266,1064
286,69804,2019-12-25,Parque Dom Pedro Shopping,Camiseta Estampa,1,196,196
287,69804,2019-12-25,Parque Dom Pedro Shopping,Camisa Linho,3,141,423
288,69871,2019-12-25,Parque Dom Pedro Shopping,Chinelo Estampa,1,74,74
289,69943,2019-12-25,Parque Dom Pedro Shopping,Relógio Xadrez,1,214,214

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65018,2019-12-01,Rio Mar Shopping Fortaleza,Cueca Estampa,1,66,66
1,65018,2019-12-01,Rio Mar Shopping Fortaleza,Sunga Xadrez,1,116,116
2,65018,2019-12-01,Rio Mar Shopping Fortaleza,Casaco Listrado,1,269,269
3,65039,2019-12-01,Rio Mar Shopping Fortaleza,Mochila,2,270,540
4,65046,2019-12-01,Rio Mar Shopping Fortaleza,Gorro Listrado,2,97,194
...,...,...,...,...,...,...,...
289,69773,2019-12-25,Rio Mar Shopping Fortaleza,Pulseira Estampa,1,87,87
290,69930,2019-12-25,Rio Mar Shopping Fortaleza,Polo Listrado,1,149,149
291,69930,2019-12-25,Rio Mar Shopping Fortaleza,Sunga Estampa,2,120,240
292,69961,2019-12-25,Rio Mar Shopping Fortaleza,Polo Xadrez,4,142,568
293,69993,2019-12-26,Rio Mar Shopping Fortaleza,Sapato Xadrez,1,368,368

## Acessar conteúdo do ZipFile sem descompactar no disco e converter para DataFrame

In [8]:
# Acessa cada arquivo contido no zipfile e transforma em Dataframe
df = None
with ZipFile('drive-download-20221008T154045Z-001.zip') as zfile:
    for filename in zfile.namelist():
        if filename.endswith('.xlsx'):
            fin = zfile.read(filename)
            df = (
                pd.read_excel(fin)
                if df is None
                else pd.concat([df, pd.read_excel(fin)], ignore_index=True)
            )
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6503 entries, 0 to 6502
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Código Venda    6503 non-null   int64
 1   Data            6503 non-null   datetime64[ns]
 2   ID Loja         6503 non-null   object
 3   Produto         6503 non-null   object
 4   Quantidade      6503 non-null   int64
 5   Valor Unitário  6503 non-null   int64
 6   Valor Final     6503 non-null   int64
dtypes: datetime64[ns](1), int64(4), object(2)
memory usage: 355.8+ KB

## Monoprocessada

In [9]:
# Acessa cada arquivo contido no zipfile e transforma em Dataframe
tempo_inicial = time.time()

with ZipFile('drive-download-20221008T154045Z-001.zip') as zfile:
    for filename in zfile.namelist():
        if 'xlsx' in filename:
            fin = zfile.read(filename)
            tabela = pd.read_excel(fin)
            # display(tabela)
            faturamento = tabela['Valor Final'].sum()
            display(
                f"Faturamento da Loja {filename.replace('.xlsx', '')} foi de R${faturamento:,.2f}."
            )
print(f'Demorou: {time.time() - tempo_inicial}')

'Faturamento da Loja Salvador Shopping foi de R$129,156.00.'

'Faturamento da Loja Shopping Midway Mall foi de R$105,269.00.'

'Faturamento da Loja Passei das Águas Shopping foi de R$112,089.00.'

'Faturamento da Loja Shopping Ibirapuera foi de R$107,907.00.'

'Faturamento da Loja Shopping Center Interlagos foi de R$103,821.00.'

'Faturamento da Loja Iguatemi Esplanada foi de R$103,342.00.'

'Faturamento da Loja Shopping Morumbi foi de R$117,936.00.'

'Faturamento da Loja Shopping Vila Velha foi de R$115,896.00.'

'Faturamento da Loja Shopping União de Osasco foi de R$116,032.00.'

'Faturamento da Loja Ribeirão Shopping foi de R$112,936.00.'

'Faturamento da Loja Shopping SP Market foi de R$110,833.00.'

'Faturamento da Loja Norte Shopping foi de R$101,491.00.'

'Faturamento da Loja Shopping Barra foi de R$103,148.00.'

'Faturamento da Loja Iguatemi Campinas foi de R$149,959.00.'

'Faturamento da Loja Shopping Eldorado foi de R$124,339.00.'

'Faturamento da Loja Shopping Iguatemi Fortaleza foi de R$124,182.00.'

'Faturamento da Loja Palladium Shopping Curitiba foi de R$120,621.00.'

'Faturamento da Loja Shopping Center Leste Aricanduva foi de R$86,156.00.'

'Faturamento da Loja Rio Mar Recife foi de R$139,869.00.'

'Faturamento da Loja Novo Shopping Ribeirão Preto foi de R$99,703.00.'

'Faturamento da Loja Shopping Recife foi de R$131,871.00.'

'Faturamento da Loja Parque Dom Pedro Shopping foi de R$122,055.00.'

'Faturamento da Loja Rio Mar Shopping Fortaleza foi de R$127,890.00.'

Demorou: 0.515289306640625

## Paralelismo com joblib

In [10]:
from joblib import Parallel, delayed

# Acessa cada arquivo contido no zipfile e transforma em Dataframe
tempo_inicial = time.time()


def listfile(zipfile=None):
    files = []
    zipfile = zipfile or 'drive-download-20221008T154045Z-001.zip'
    with ZipFile(zipfile) as zfile:
        for filename in zfile.namelist():
            if 'xlsx' in filename:
                files.append(
                    (filename.replace('.xlsx', ''), zfile.read(filename))
                )
    return files


# print(listfile())

for (filename, content) in listfile():
    tabela = pd.read_excel(content)
    faturamento = tabela['Valor Final'].sum()
    print(f'Faturamento da Loja {filename} foi de R${faturamento:,.2f}.')

print(f'Demorou: {time.time() - tempo_inicial}')

Faturamento da Loja Salvador Shopping foi de R$129,156.00.
Faturamento da Loja Shopping Midway Mall foi de R$105,269.00.
Faturamento da Loja Passei das Águas Shopping foi de R$112,089.00.
Faturamento da Loja Shopping Ibirapuera foi de R$107,907.00.
Faturamento da Loja Shopping Center Interlagos foi de R$103,821.00.
Faturamento da Loja Iguatemi Esplanada foi de R$103,342.00.
Faturamento da Loja Shopping Morumbi foi de R$117,936.00.
Faturamento da Loja Shopping Vila Velha foi de R$115,896.00.
Faturamento da Loja Shopping União de Osasco foi de R$116,032.00.
Faturamento da Loja Ribeirão Shopping foi de R$112,936.00.
Faturamento da Loja Shopping SP Market foi de R$110,833.00.
Faturamento da Loja Norte Shopping foi de R$101,491.00.
Faturamento da Loja Shopping Barra foi de R$103,148.00.
Faturamento da Loja Iguatemi Campinas foi de R$149,959.00.
Faturamento da Loja Shopping Eldorado foi de R$124,339.00.
Faturamento da Loja Shopping Iguatemi Fortaleza foi de R$124,182.00.
Faturamento da Loja Palladium Shopping Curitiba foi de R$120,621.00.
Faturamento da Loja Shopping Center Leste Aricanduva foi de R$86,156.00.
Faturamento da Loja Rio Mar Recife foi de R$139,869.00.
Faturamento da Loja Novo Shopping Ribeirão Preto foi de R$99,703.00.
Faturamento da Loja Shopping Recife foi de R$131,871.00.
Faturamento da Loja Parque Dom Pedro Shopping foi de R$122,055.00.
Faturamento da Loja Rio Mar Shopping Fortaleza foi de R$127,890.00.
Demorou: 0.46489429473876953

In [12]:
from joblib import Parallel, delayed
from pprint import pprint

# Acessa cada arquivo contido no zipfile e transforma em Dataframe
tempo_inicial = time.time()


def listfile(zipfile=None):
    files = []
    zipfile = zipfile or 'drive-download-20221008T154045Z-001.zip'
    with ZipFile(zipfile) as zfile:
        for filename in zfile.namelist():
            if 'xlsx' in filename:
                files.append(
                    (filename.replace('.xlsx', ''), zfile.read(filename))
                )
    return files


def calcular_faturamento(file):
    filename, content = file
    tabela = pd.read_excel(content)
    faturamento = tabela['Valor Final'].sum()
    return f'Faturamento da Loja {filename} foi de R${faturamento:,.2f}.'


# print(type(listfile()[0]))
resultado = Parallel(n_jobs=3)(
    delayed(calcular_faturamento)(arquivo) for arquivo in listfile()
)
pprint(resultado)
print(f'Demorou: {time.time() - tempo_inicial}')

['Faturamento da Loja Salvador Shopping foi de R$129,156.00.',
 'Faturamento da Loja Shopping Midway Mall foi de R$105,269.00.',
 'Faturamento da Loja Passei das Águas Shopping foi de R$112,089.00.',
 'Faturamento da Loja Shopping Ibirapuera foi de R$107,907.00.',
 'Faturamento da Loja Shopping Center Interlagos foi de R$103,821.00.',
 'Faturamento da Loja Iguatemi Esplanada foi de R$103,342.00.',
 'Faturamento da Loja Shopping Morumbi foi de R$117,936.00.',
 'Faturamento da Loja Shopping Vila Velha foi de R$115,896.00.',
 'Faturamento da Loja Shopping União de Osasco foi de R$116,032.00.',
 'Faturamento da Loja Ribeirão Shopping foi de R$112,936.00.',
 'Faturamento da Loja Shopping SP Market foi de R$110,833.00.',
 'Faturamento da Loja Norte Shopping foi de R$101,491.00.',
 'Faturamento da Loja Shopping Barra foi de R$103,148.00.',
 'Faturamento da Loja Iguatemi Campinas foi de R$149,959.00.',
 'Faturamento da Loja Shopping Eldorado foi de R$124,339.00.',
 'Faturamento da Loja Shopping Iguatemi Fortaleza foi de R$124,182.00.',
 'Faturamento da Loja Palladium Shopping Curitiba foi de R$120,621.00.',
 'Faturamento da Loja Shopping Center Leste Aricanduva foi de R$86,156.00.',
 'Faturamento da Loja Rio Mar Recife foi de R$139,869.00.',
 'Faturamento da Loja Novo Shopping Ribeirão Preto foi de R$99,703.00.',
 'Faturamento da Loja Shopping Recife foi de R$131,871.00.',
 'Faturamento da Loja Parque Dom Pedro Shopping foi de R$122,055.00.',
 'Faturamento da Loja Rio Mar Shopping Fortaleza foi de R$127,890.00.']
Demorou: 0.17247843742370605